server:
  port: 6666

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_gateway_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      INDENT_OUTPUT: true

app:
  jwt:
    secret: EOq6kdcXhxt5maFrGSG4g2EuDTwiUqa4A4ZRAJf3FGg=
    expirationMs: 86400000
